# Generated by Django 3.0.1 on 2020-01-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_name', models.CharField(max_length=50)),
                ('active_flag', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(default='user', max_length=10)),
                ('active_flag', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=55)),
                ('mobile', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('fk_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angularapi.UserLogin')),
            ],
        ),
        migrations.CreateModel(
            name='Complaintreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('active_flag', models.IntegerField(default=1)),
                ('fk_priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angularapi.ComplaintPriority')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angularapi.UserLogin')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/')),
                ('fk_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angularapi.Complaintreg')),
            ],
        ),
    ]
