# Generated by Django 3.0.1 on 2020-01-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angularapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintpriority',
            name='display_style',
            field=models.CharField(default='alert alert-info', max_length=35),
        ),
    ]
